version: '3.8'

services:
  microservice:
    build: .
    container_name: microservice-nestjs
    environment:
      - TCP_HOST=0.0.0.0
      - TCP_PORT=3001
    ports:
      - "3001:3001"
    restart: unless-stopped
